
package Proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BanqueService", targetNamespace = "http://WebService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueService {


    /**
     * 
     * @param arg0
     * @return
     *     returns Proxy.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompte", targetNamespace = "http://WebService/", className = "Proxy.GetCompte")
    @ResponseWrapper(localName = "getCompteResponse", targetNamespace = "http://WebService/", className = "Proxy.GetCompteResponse")
    @Action(input = "http://WebService/BanqueService/getCompteRequest", output = "http://WebService/BanqueService/getCompteResponse")
    public Compte getCompte(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List<Proxy.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getComptes", targetNamespace = "http://WebService/", className = "Proxy.GetComptes")
    @ResponseWrapper(localName = "getComptesResponse", targetNamespace = "http://WebService/", className = "Proxy.GetComptesResponse")
    @Action(input = "http://WebService/BanqueService/getComptesRequest", output = "http://WebService/BanqueService/getComptesResponse")
    public List<Compte> getComptes();

    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod(operationName = "ConvertDh")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ConvertDh", targetNamespace = "http://WebService/", className = "Proxy.ConvertDh")
    @ResponseWrapper(localName = "ConvertDhResponse", targetNamespace = "http://WebService/", className = "Proxy.ConvertDhResponse")
    @Action(input = "http://WebService/BanqueService/ConvertDhRequest", output = "http://WebService/BanqueService/ConvertDhResponse")
    public double convertDh(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

}
